import type { Strategy } from "./types"

export const STRATEGIES: Strategy[] = [
    {
        id: "hype-sentiment",
        address: "0xdf76daF4e916399E60A69D05d1C038Fbb664b9aB",
        title: "Hype - Sentiment Strategy",
        subtitle: "Signals-driven directional exposure",
        description: "Leverages real-time social sentiment and HyperLiquid perp liquidity for fast directional positioning.",
        focus: "BTC Perp",
        asset: "BTC",
        risk: "Medium",
        strategyType: "Sentiment",
    },
    {
        id: "hype-hyperlend",
        address: "0xbc5a1e5833dac6ce165c26f44c8b51284df53391",
        title: "Hype - Hyperlend Strategy",
        subtitle: "Capital-efficient looping",
        description: "Optimizes LTV by cycling collateral between HyperLend and HyperLiquid execution.",
        focus: "ETH Loop",
        asset: "ETH",
        risk: "Low",
        strategyType: "Hyperlend",
    },
    {
        id: "khype-sentiment",
        address: "0xdf76daF4e916399E60A69D05d1C038Fbb664b9aB",
        title: "KHype - Sentiment Strategy",
        subtitle: "Multi-venue hedged sentiment",
        description: "Combines cross-venue hedges with momentum execution for lower variance.",
        focus: "Basket",
        asset: "SOL",
        risk: "Medium",
        strategyType: "Sentiment",
    },
    {
        id: "khype-hyperlend",
        address: "0xbc5a1e5833dac6ce165c26f44c8b51284df53391",
        title: "KHype - Hyperlend Strategy",
        subtitle: "Delta-neutral carry",
        description: "Deploys vault assets into carry trades while keeping health factor targets intact.",
        focus: "Stable Carry",
        asset: "USDC",
        risk: "Low",
        strategyType: "Hyperlend",
    },
]
